platform :ios, '12.0'
use_frameworks!

def base_db_dependencies
    pod 'Firebase/Messaging', '10.6.0'
    pod 'TBXML', '1.5'
    pod 'AFNetworking', '4.0.1'
    pod 'GTMNSStringHTMLAdditions', '0.2.1'
    pod 'Mantle', '2.2.0'
    pod 'GoogleMaps', '6.2.1'
    pod 'MBProgressHUD', '1.2.0'
    pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.31.3'
end

target 'MeinBahnhofOpenSource' do
    base_db_dependencies
end

#fix for xcode12 warnings with older pods
post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            end
         end
     end
end

