platform :ios, '14.0'
use_frameworks!

def base_db_dependencies
  pod 'Firebase/Messaging', '10.29.0'
  pod 'TBXML', '1.5'
  pod 'AFNetworking', '4.0.1'
  pod 'GTMNSStringHTMLAdditions', '0.2.1'
  pod 'Mantle', '2.2.0'
  pod 'GoogleMaps', '8.4.0'
  pod 'MBProgressHUD', '1.2.0'
end

target 'MeinBahnhofOpenSource' do
    base_db_dependencies
end

#fix for xcode14 warnings with older pods
post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 14.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            end
         end
     end
end

