platform :ios, '12.0'
use_frameworks!

def base_db_dependencies
    pod 'TBXML', '~> 1.5'
    pod 'AFNetworking', '~> 4.0'
    pod 'GTMNSStringHTMLAdditions', '~> 0.2.1'
    pod 'Mantle', '~> 2.1.6'
    pod 'GoogleMaps', '4.2.0'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '6.0.7'
end

target 'MeinBahnhofOpenSource' do
    base_db_dependencies
end

#fix for xcode12 warnings with older pods
post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            end
         end
     end
end

